pipeline:
  build:
    image: snowcookie:laravel-env
    volumes:
      - /home/snow/Giftpack-Migration:database/migrations/Giftpack
    commands:
      - ls database/migrations/Giftpack
      - composer install
      - mv .env.example .env
      - php artisan key:generate
      - vendor/bin/phpunit --debug --colors