pipeline:
  build:
    image: snowcookie:laravel-env
    volumes:
      - /home/snow/Giftpack-Migration:/drone/src/github.com/snowshana/drone_test/commit/${DRONE_COMMIT_SHA}/database/migrations/Giftpack
    commands:
      - ls database/migrations
      - composer install
      - mv .env.example .env
      - php artisan key:generate
      - vendor/bin/phpunit --debug --colors