pipeline:
  build:
    image: snowcookie:laravel-env
    commands:
      - composer install
      - mv .env.example .env
      - php artisan key:generate
      - php artisan migrate
      - vendor/bin/phpunit --debug --colors