pipeline:
  build:
    image: php:7.0-cli
    commands:
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php
      - composer install
      - php artisan migrate
      - vendor/phpunit/phpunit/phpunit --debug --colors